base_object:
  code: load_file_code_js
  credentials: &id001
  - provider: salesforce
  description: Lookup insight about the account given a GPT question
  exec_type: trigger
  mode: null
  name: Sample Function
  packages: &id002
  - layer_arn: arn:aws:lambda:us-east-1:580674011299:layer:jsforce-1_11_0:1
  runtime: nodejs
  variables: &id003
  - name: Dude
    value: Car
  - name: Foo
    value: Bar
development:
  account: 18614
  host: app.ctmdev.us
  object:
    code: load_file_code_js
    credentials: *id001
    description: Lookup insight about the account given a GPT question
    exec_type: trigger
    id: LDA8CA4483EED6CEF9EA0E0D4EDCFC4A89D6F43C0096467A7F3
    mode: null
    name: Sample Function
    packages: *id002
    runtime: nodejs
    variables: *id003
production:
  account: 18614
  host: app.calltrackingmetrics.com
  object:
    code: load_file_code_js
    credentials: *id001
    description: Lookup insight about the account given a GPT question
    exec_type: trigger
    id: TODO
    mode: null
    name: Sample Function
    packages: *id002
    runtime: nodejs
    variables: *id003
staging:
  account: 18614
  host: app.calltrackingmetrics.com
  object:
    code: load_file_code_js
    credentials: *id001
    description: Lookup insight about the account given a GPT question
    exec_type: trigger
    id: TODO
    mode: null
    name: Sample Function
    packages: *id002
    runtime: nodejs
    variables: *id003
