#!/usr/bin/env ruby

BRANCHES = %w(release-production release-staging release-development)

current_branch = `git rev-parse --abbrev-ref HEAD`.chomp

if BRANCHES.include?(current_branch)
  require 'yaml'
  require 'json'

  env = current_branch.split('-').last
  config = if RUBY_VERSION.to_f >= 3.1
    YAML.load_file("config.yml", aliases: true)[env]
  else
    YAML.load_file("config.yml")[env]
  end

  host = config['host']
  account = config['account']
  object  = config['object']
  if object.key?('code')
    object['code'] = File.read('code.js')
  end

  # Prompt the user for the API key
  puts "Enter your API key for branch #{current_branch}:"
  api_key = gets.chomp

  puts "deploying #{JSON.pretty_generate(object)}"

  system(%(curl -u#{api_key} -XPATCH -H'Content-Type:application/json' 'https://#{host}/api/v1/accounts/#{account}/lambdas/#{object['id']}' -d'#{object.to_json}'))
end
