#!/usr/bin/env ruby

# Define the path to the config file
CONFIG_FILE = "config.yml"

# Use yaml-lint to validate the YAML format
yaml_lint_output = `yaml-lint #{CONFIG_FILE}`
if $?.exitstatus != 0
  puts "Error: Invalid YAML format in #{CONFIG_FILE}:"
  puts yaml_lint_output
  exit 1
end

# Use the ruby YAML library to load the config file to ensure it doesn't crash
require 'yaml'
begin
  config = if RUBY_VERSION.to_f >= 3.1
    YAML.load_file("config.yml", aliases: true)
  else
    YAML.load_file("config.yml")
  end
  ['development','staging','production'].each {|env_key|
    cfg = config[env_key]
    if cfg.nil?
      puts "Error: Missing '#{env_key}' key in #{CONFIG_FILE}"
      exit 1
    end
    ['host','object','account'].each {|key|
      if cfg[key].nil?
        puts "Error: Missing '#{key}' key in #{CONFIG_FILE} for #{env_key}\n\n#{cfg.inspect}"
        exit 1
      end
    }

    object  = cfg['object']
    if object.key?('code')
      if !File.exist?('code.js')
        puts "Error: Missing code.js file"
        exit 1
      end
      if !system("/usr/bin/env node -c code.js")
        puts "Error: code.js is not valid JavaScript"
        exit 1
      end
    end
  }
rescue => e
  puts "Error: Failed to load #{CONFIG_FILE}: #{e.message}"
  exit 1
end
